version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:18.15.0-buster

jobs:
  install-dependencies:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install

  lint:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Run ESLint
          command: npx eslint .

  test:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: npm test

  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Build the project
          command: npm run build

  deploy:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Deploy to production
          command: |
            echo "Deploying to production..."
            # TODO: Add deployment script

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - install-dependencies
      - lint:
          requires:
            - install-dependencies
      - test:
          requires:
            - lint
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
