version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:23.5.0

jobs:
  build:
    docker:
      - image: cimg/node:23.5.0
    steps:
      - checkout
      - run: node --version
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Install Jest
          command: npm install jest supertest --save-dev
      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
