name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.5.0'

      - name: Install dependencies
        run: npm install

      - name: Install Jest and Supertest
        run: npm install jest supertest --save-dev

      - name: Run tests
        run: npm test

      - name: Output test results
        if: failure()
        run: cat ./test-results.txt || true
